include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable some rules for example code
    avoid_print: false
    prefer_const_constructors: false
    use_build_context_synchronously: false