include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    # These are style-only and currently produce a lot of noise in tests.
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
