# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error

  ignore:
    - "test/**/*"
    - "lib/src/models/**/*"  # データクラスは除外
    - "lib/offline_web_proxy.dart"  # エクスポートファイルは除外

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true